INSERT INTO `states` (`id`, `abbreviation`, `name`)
VALUES
  (1,'AL','Alabama'),
  (2,'AK','Alaska'),
  (3,'AZ','Arizona'),
  (4,'AR','Arkansas'),
  (5,'CA','California'),
  (6,'CO','Colorado'),
  (7,'CT','Connecticut'),
  (8,'DE','Delaware'),
  (9,'FL','Florida'),
  (10,'GA','Georgia'),
  (11,'HI','Hawaii'),
  (12,'IA','Iowa'),
  (13,'ID','Idaho'),
  (14,'IL','Illinois'),
  (15,'IN','Indiana'),
  (16,'KS','Kansas'),
  (17,'KY','Kentucky'),
  (18,'LA','Louisiana'),
  (19,'MA','Massachusetts'),
  (20,'MD','Maryland'),
  (21,'ME','Maine'),
  (22,'MI','Michigan'),
  (23,'MN','Minnesota'),
  (24,'MS','Mississippi'),
  (25,'MO','Missouri'),
  (26,'MT','Montana'),
  (27,'NC','North Carolina'),
  (28,'ND','North Dakota'),
  (29,'NE','Nebraska'),
  (30,'NH','New Hampshire'),
  (31,'NJ','New Jersey'),
  (32,'NV','Nevada'),
  (33,'NM','New Mexico'),
  (34,'NY','New York'),
  (35,'OH','Ohio'),
  (36,'OK','Oklahoma'),
  (37,'OR','Oregon'),
  (38,'PA','Pennsylvania'),
  (39,'RI','Rhode Island'),
  (40,'SC','South Carolina'),
  (41,'SD','South Dakota'),
  (42,'TN','Tennessee'),
  (43,'TX','Texas'),
  (44,'UT','Utah'),
  (45,'VA','Virginia'),
  (46,'VT','Vermont'),
  (47,'WA','Washington'),
  (48,'WI','Wisconsin'),
  (49,'WV','West Virginia'),
  (50,'WY','Wyoming'),
  (51,'DC','District of Columbia'),
  (52,'PR','Puerto Rico'),
  (53,'VI','U.S. Virgin Islands'),
  (54,'AS','American Samoa'),
  (55,'GU','Guam'),
  (56,'MP','Northern Mariana Islands');
